Bugfix in extract_nc_time function
Popped out when it tried to operate on amip/HadGem/ua
2 files, one was only one time unit long.

temp = NUMBER
np.size(temp,0)
!!! ERROR!!!!

Error (below) because size along zeroth axis not defined

+++++++++++++ Error Output +++++++++++++++

Extracting file number 2 of 2
The time size is ()
Traceback (most recent call last):
  File "SPOOKIE-data-interp.py", line 47, in <module>
    time_array = extract_nc_time(files, tmp_array)
  File "/Users/camcairns/Dropbox/py_modules/nc_data/nc_data.py", line 90, in extract_nc_time
    tmp_array[model_size:model_size+np.size(temp,0)] = temp
  File "/Users/camcairns/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2536, in size
    return a.shape[axis]
IndexError: tuple index out of range